POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "beste@gmail.com",
  "password": "123456"
}
### Find particular user with id
GET http://localhost:3000/auth/1

### Update user with id
PATCH http://localhost:3000/auth/1
content-type: application/json

{
  "email": "bbbb@gmail.com"
}

### Delete user with id
DELETE http://localhost:3000/auth/1